// All facts in this file are sourced directly from the ClaimsLake repository
// (README.md, CHANGELOG.md, docs/, sql/, dbt/, airflow/, docker-compose.yml,
// .github/workflows/ci.yml) as of the v1.0.0 release. Nothing here is invented.
// Repo: https://github.com/Gundabathina/claimslake

export const REPO_URL = "https://github.com/Gundabathina/claimslake";
export const PORTFOLIO_URL = "https://prem-portfolio-nu.vercel.app";
export const AUTHOR = "Gundabathina";

export const hero = {
  eyebrow: "Data engineering portfolio project · synthetic data only",
  title: "ClaimsLake",
  subtitle: "Healthcare Claims Data Engineering Platform",
  description:
    "An end-to-end, production-style pipeline that ingests, cleans, models, and analyzes synthetic healthcare claims data on a medallion (Bronze → Silver → Gold) architecture — Python ingestion, PySpark, dbt-duckdb, Airflow orchestration, Docker, and a Terraform AWS reference architecture.",
  ctas: [
    { label: "Explore the platform", href: "#how-it-works", primary: true },
    { label: "View GitHub", href: REPO_URL, primary: false, external: true },
  ],
  stats: [
    { value: "26", label: "Bronze ingestion tests" },
    { value: "17", label: "PySpark Silver tests" },
    { value: "35", label: "Curated SQL queries" },
    { value: "PASS = 14", label: "dbt tests" },
  ],
};

export const layers = [
  {
    id: "bronze",
    name: "Bronze",
    color: "bronze",
    tagline: "Raw, string-typed, nothing lost",
    description:
      "Config-driven Python ingestion (full + incremental) lands source files as raw Parquet, partitioned by ingestion date. Every column stays string-typed on purpose — casting happens later, in Silver, where invalid values can be routed rather than silently corrupted. Retry handling, structured logging, and per-batch metadata tracking wrap every load.",
    bullets: [
      "Sources declared in ingestion/config/sources.yaml",
      "Full + incremental load support with retries",
      "Per-batch metadata tracking and structured logging",
      "Output: raw Parquet, all columns as strings",
    ],
    tech: ["Python 3.11", "PyArrow/Parquet", "YAML config"],
  },
  {
    id: "silver",
    name: "Silver",
    color: "silver",
    tagline: "Typed, standardized, deduplicated, validated",
    description:
      "A PySpark layer casts explicit schemas, standardizes fields (e.g. trimming/upper-casing state codes), and runs deterministic two-stage deduplication on business keys. Business-rule validation checks things like future dates of birth or invalid state codes — records that fail are routed to a quarantine path with a reason and timestamp instead of being dropped. Non-fatal issues are flagged with data-quality columns and kept.",
    bullets: [
      "Explicit schemas, type casting, standardization",
      "Deterministic two-stage deduplication",
      "Quarantine path with rejection reason + timestamp",
      "Late-arriving claim flagging; referential-integrity checks",
    ],
    tech: ["PySpark", "JDK 17", "Parquet"],
  },
  {
    id: "gold",
    name: "Gold",
    color: "gold",
    tagline: "A dbt star schema, queried straight from Parquet",
    description:
      "dbt-duckdb reads the Silver Parquet output directly — no separate load step. Models build fact_claims plus dim_member and dim_provider, the latter carrying SCD Type 2 history so provider network-status changes are preserved over time, not overwritten. Every model is covered by dbt tests.",
    bullets: [
      "fact_claims, dim_member, dim_provider (SCD2)",
      "dbt-duckdb reads Silver Parquet directly",
      "dbt tests: PASS = 14 (verified locally)",
      "Feeds the 35-query analytical SQL layer",
    ],
    tech: ["dbt-duckdb", "DuckDB"],
  },
];

export const architectureNodes = [
  {
    id: "sources",
    label: "Synthetic source data",
    detail: "members · providers · diagnoses · claims — generated by scripts/generate_synthetic_data.py",
    group: "source",
  },
  {
    id: "ingestion",
    label: "Python ingestion",
    detail: "Config-driven full/incremental loads, retries, logging, metadata tracking",
    group: "compute",
  },
  {
    id: "bronze",
    label: "Bronze (raw Parquet)",
    detail: "String-typed, partitioned by ingestion date",
    group: "storage",
  },
  {
    id: "spark",
    label: "PySpark Silver",
    detail: "Type, standardize, deduplicate, validate — quarantine on failure",
    group: "compute",
  },
  {
    id: "airflow",
    label: "Apache Airflow",
    detail: "Orchestrates ingest → Silver → dbt build → dbt test (claimslake_pipeline DAG)",
    group: "orchestration",
  },
  {
    id: "minio",
    label: "MinIO (S3-compatible)",
    detail: "Local object storage substitute for S3, run via Docker Compose",
    group: "storage",
  },
  {
    id: "dbt",
    label: "dbt-duckdb",
    detail: "Builds the Gold star schema directly from Silver Parquet",
    group: "compute",
  },
  {
    id: "sql",
    label: "SQL analytics",
    detail: "35 curated queries across claims, finance, members, providers, data quality",
    group: "analytics",
  },
  {
    id: "terraform",
    label: "Terraform (AWS reference)",
    detail: "S3 + Glue + Athena + IAM — CI-validated, never applied",
    group: "iac",
  },
  {
    id: "cicd",
    label: "GitHub Actions CI/CD",
    detail: "4 parallel jobs: unit, PySpark, Airflow, dbt parse — plus a Terraform validation workflow",
    group: "cicd",
  },
];

export const pipelineDemoStages = [
  {
    id: "check_prerequisites",
    title: "Check prerequisites",
    description: "Verifies PySpark, dbt, and Java are available; ensures Bronze/Silver/quarantine/metrics directories exist.",
  },
  {
    id: "bronze_ingestion",
    title: "Bronze ingestion",
    description: "Runs the Python ingestion engine against configured sources, writing raw Parquet to the Bronze layer.",
  },
  {
    id: "silver_processing",
    title: "Silver processing",
    description: "PySpark types, standardizes, deduplicates, and validates records; invalid rows are quarantined.",
  },
  {
    id: "gold_dbt_build",
    title: "Gold dbt build",
    description: "dbt-duckdb builds fact_claims, dim_member, and dim_provider (SCD2) directly from Silver Parquet.",
  },
  {
    id: "validate_outputs",
    title: "Validate outputs",
    description: "Confirms every expected artifact exists (Bronze/Silver Parquet, quarantine output, metrics, Gold DuckDB file).",
  },
];

export const evidence = [
  {
    title: "Docker Compose",
    status: "Verified locally",
    detail:
      "A full docker compose down -v && docker compose up --build run brings up Postgres, initializes the Airflow metadata DB, completes airflow-init, starts the webserver + scheduler, and runs the PySpark test suite inside the app container.",
    link: { label: "docker-compose.yml", href: `${REPO_URL}/blob/main/docker-compose.yml` },
  },
  {
    title: "Airflow orchestration",
    status: "DAG tests: 7 passing (verified locally)",
    detail:
      "The claimslake_pipeline DAG wires check_prerequisites → bronze_ingestion → silver_processing → gold_dbt_build → validate_outputs, reusing the same production functions as scripts/run_pipeline.py.",
    link: { label: "airflow/dags/claimslake_pipeline.py", href: `${REPO_URL}/blob/main/airflow/dags/claimslake_pipeline.py` },
  },
  {
    title: "PySpark Silver tests",
    status: "17 tests passing (verified locally)",
    detail: "Covers cleaners, deduplication, the Silver pipeline, and validators — runs against JDK 17.",
    link: { label: "tests/pyspark/", href: `${REPO_URL}/tree/main/tests/pyspark` },
  },
  {
    title: "dbt build + tests",
    status: "PASS = 14 (verified locally)",
    detail: "fact_claims, dim_member, and dim_provider (SCD2) all build and pass dbt's schema/data tests via dbt-duckdb.",
    link: { label: "dbt/models/marts/", href: `${REPO_URL}/tree/main/dbt/models/marts` },
  },
  {
    title: "SQL analytics",
    status: "35 curated queries",
    detail: "Grouped into claims, finance, members, providers, and data-quality domains, each documented with a business question.",
    link: { label: "docs/analytics_catalog.md", href: `${REPO_URL}/blob/main/docs/analytics_catalog.md` },
  },
  {
    title: "GitHub Actions CI",
    status: "4 application jobs green",
    detail: "unit-tests, pyspark-tests, airflow-tests, and dbt-checks run in parallel on every push; a separate path-filtered workflow validates Terraform.",
    link: { label: ".github/workflows/ci.yml", href: `${REPO_URL}/blob/main/.github/workflows/ci.yml` },
  },
];

export const verifiedResults = [
  { milestone: "Repository scaffolding", status: "Complete" },
  { milestone: "Synthetic data generation", status: "Complete" },
  { milestone: "Bronze ingestion (Python)", status: "Complete — 26 tests passing" },
  { milestone: "Silver transformations (PySpark)", status: "Complete — 17 tests passing" },
  { milestone: "Gold star schema (dbt-duckdb)", status: "Complete — dbt PASS = 14" },
  { milestone: "Analytical SQL layer", status: "Complete — 35 queries" },
  { milestone: "Airflow orchestration", status: "Complete — 7 DAG tests passing" },
  { milestone: "GitHub Actions CI", status: "Complete — 4 jobs green" },
  { milestone: "Terraform AWS reference architecture", status: "CI-validated — never applied" },
  { milestone: "End-to-end local execution", status: "Complete" },
  { milestone: "Docker Compose full stack", status: "Verified locally" },
  { milestone: "Streaming (Kafka)", status: "Optional future enhancement — not implemented" },
  { milestone: "AWS deployment", status: "Reference architecture only — not applied" },
];

export const decisions = [
  {
    q: "Why Docker?",
    a: "Docker Compose reproduces the whole local stack — MinIO, Postgres, and Airflow — the same way on any machine, so the pipeline isn't dependent on one developer's local setup.",
  },
  {
    q: "Why Airflow?",
    a: "The pipeline has real task dependencies (ingest → Silver → dbt build → dbt test) and needs retries and execution timeouts. Airflow expresses that as a DAG instead of a shell script, and the DAG reuses the exact same production functions as the standalone pipeline runner — orchestration and business logic stay decoupled.",
  },
  {
    q: "Why PySpark?",
    a: "Silver-layer work — typing, standardization, deterministic two-stage deduplication, and validation — is exactly the kind of transformation Spark is built for, and it's the processing engine most claims-scale data platforms actually run in production.",
  },
  {
    q: "Why dbt?",
    a: "dbt turns the Gold layer into version-controlled, tested SQL instead of ad hoc scripts. dbt-duckdb specifically lets it read the Silver Parquet output directly with no separate load step, keeping the whole project runnable locally while still exercising real dbt modeling, sources, and tests.",
  },
  {
    q: "Why medallion architecture (Bronze/Silver/Gold)?",
    a: "It separates concerns cleanly: Bronze preserves raw source data for auditability and reprocessing, Silver applies cleaning and validation, and Gold delivers business-ready models. Each layer can be rebuilt independently, which makes debugging and backfills straightforward.",
  },
  {
    q: "Why Terraform (as a reference architecture, not a deployment)?",
    a: "Terraform documents, in code, exactly how the local design would map to AWS — S3 for the Bronze/Silver/Gold/quarantine layers, Glue for cataloging, Athena for serverless SQL, and least-privilege IAM. It's validated in CI (fmt, init, validate) so the configuration is provably sound, but plan/apply require AWS credentials and would create real, billable resources — so it's deliberately never applied.",
  },
  {
    q: "Why synthetic healthcare data?",
    a: "Claims data is protected health information. Using generated synthetic members, providers, diagnoses, and claims (structured similarly to CMS synthetic public-use files and the Synthea generator) makes it possible to demonstrate realistic healthcare-claims engineering — denials, quarantine, SCD2 provider history — without touching any real patient data.",
  },
];

export const sampleData = {
  bronze: {
    label: "Bronze — raw source rows (data/sample/claims_batch_1_sample.csv)",
    columns: ["claim_id", "member_id", "provider_id", "diagnosis_code", "service_date", "billed_amount", "paid_amount", "claim_status", "denial_reason"],
    rows: [
      ["C216AE7A8E7B7", "M1000021", "P100008", "R51", "2025-02-15", "7193.37", "6567.47", "Paid", ""],
      ["CBA770CA8CD09", "M1000040", "P100005", "N39.0", "2026-01-08", "4058.20", "0", "Denied", "Out-of-network provider"],
    ],
  },
  silver: {
    label: "Silver — standardized (illustrative shape, from README)",
    columns: ["member_id", "gender", "state", "plan_type", "has_missing_zip"],
    rows: [["M0001", "F", "CA", "PPO", "false"]],
    note: "Illustrative placeholder showing the shape of the output, not a committed execution result — matches README's Sample Outputs section.",
  },
  gold: {
    label: "Gold — fact_claims (illustrative shape, from README)",
    columns: ["claim_id", "member_id", "provider_id", "billed_amount", "paid_amount", "claim_status"],
    rows: [["C10001", "M0001", "P0007", "1200.00", "950.00", "PAID"]],
    note: "Illustrative placeholder showing the shape of the output, not a committed execution result — matches README's Sample Outputs section.",
  },
};

export const sqlQueries = [
  {
    id: "q4",
    domain: "Claims",
    title: "Q4 — Denial percentage",
    question: "What share of claims are denied?",
    why: "Denial rate is a headline healthcare KPI; a high rate often signals eligibility, coding, or authorization problems.",
    sql: `select
    sum(is_denied)                              as denied_claims,
    count(*)                                     as total_claims,
    round(100.0 * sum(is_denied) / count(*), 2)  as denial_pct
from fact_claims;`,
  },
  {
    id: "q13",
    domain: "Finance",
    title: "Q13 — Total adjustments (billed not paid)",
    question: "How much of billed charges were not paid?",
    why: "fact_claims has no raw adjustment_amount column, so the honest, real column (unpaid_amount = billed − paid) is used instead of inventing one.",
    sql: `select round(sum(unpaid_amount), 2) as total_adjustments
from fact_claims;`,
  },
  {
    id: "q29",
    domain: "Providers",
    title: "Q29 — Provider historical versions (SCD2)",
    question: "How many historical versions does each provider have?",
    why: "Demonstrates that dim_provider actually carries SCD Type 2 history rather than overwriting provider attributes.",
    sql: `select
    provider_id,
    count(*) as version_count
from dim_provider
group by provider_id
order by version_count desc;`,
  },
  {
    id: "q31",
    domain: "Data Quality",
    title: "Q31 — Quarantined claims summary",
    question: "How many claim records were rejected, and for which reasons?",
    why: "Quarantine volume is the front-line signal of upstream data-quality problems — a spike usually means a source format changed.",
    sql: `select
    rejection_reason,
    count(*) as quarantined_records
from read_parquet('silver/quarantine/claims/**/*.parquet', union_by_name => true)
group by rejection_reason
order by quarantined_records desc;`,
  },
];

export const techStack = [
  { layer: "Language", tech: "Python 3.11", purpose: "Ingestion, utilities, tests" },
  { layer: "Processing", tech: "PySpark", purpose: "Bronze → Silver transformations" },
  { layer: "Lake storage", tech: "Parquet (local); MinIO (S3-compatible)", purpose: "Columnar storage, local S3 substitute" },
  { layer: "Modeling", tech: "dbt (dbt-duckdb)", purpose: "Gold star schema, tests, docs" },
  { layer: "Query engine", tech: "DuckDB", purpose: "Reads Silver Parquet directly; runs Gold + analytics" },
  { layer: "Orchestration", tech: "Apache Airflow", purpose: "DAG scheduling, retries, dependencies" },
  { layer: "Analytics", tech: "SQL", purpose: "35 curated analytical queries" },
  { layer: "Containerization", tech: "Docker & Docker Compose", purpose: "Reproducible local environment" },
  { layer: "IaC", tech: "Terraform (AWS: S3, Glue, Athena, IAM)", purpose: "Cloud reference architecture (not applied)" },
  { layer: "CI", tech: "GitHub Actions", purpose: "Tests + dbt parse + Terraform validation" },
  { layer: "Testing", tech: "pytest, dbt tests", purpose: "Unit and data-quality testing" },
];

export const ctas = {
  source: { label: "View source code", href: REPO_URL },
  docs: { label: "Read documentation", href: `${REPO_URL}#readme` },
  portfolio: { label: "Portfolio", href: PORTFOLIO_URL },
};

export const limitations = [
  "All data is synthetic; no real patient, member, or claims data is used anywhere.",
  "The Terraform AWS architecture is reference-only and has never been planned or applied — it creates no AWS resources or cost.",
  "Streaming (Kafka) is not implemented; it remains optional future work.",
  "The pipeline simulation on this page replays the real DAG's stage names and order — it does not execute Spark or dbt in your browser.",
];
